insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 692','248호','젓가락 2개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 369-5','93호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 양천구 신정동 282-10','49호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 369-1','39호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 338','55호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 110-5','29호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 1267','257호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 427-5','270호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 동교동 163-9','82호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 마포구 동교동 165-8','65호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 90-2','17호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 338','97호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 501-5','231호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 170-10','226호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 387-21','58호','젓가락 3개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 98-1','158호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 473','294호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 212-8','150호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 369-10','215호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 29-22','88호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 444-2','186호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 426-167','290호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 692','51호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 393-7','239호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 314-10','146호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 87-1','150호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 망원동 416-49','239호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 310-14','174호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 369-44','65호','젓가락 4개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 90-8','249호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 437-1','61호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 314-11','214호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 71-15','251호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 망원1동 414-20','179호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 339-9','104호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 40-10','237호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 314-8','85호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 41-7','298호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 영등포구 대림동 1116-15','58호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 304-1','24호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 370-8','139호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 337','167호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 74-30','61호','젓가락 5개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 648','148호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 371-3','56호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 313-49','9호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 146-6','7호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 437-1','267호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 146-18','32호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 528-7','49호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 292-247','56호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 367-9','290호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 338','3호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 292-32','185호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 472','235호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 1262','158호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 92-2','41호','젓가락 6개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 770-40','101호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 337','112호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 364-22','117호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 363-21','169호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 314-11','239호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 망원동 377-1','135호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(8,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 393-20','40호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 393-15','48호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 27-4','121호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 마포구 성산동 253-16','219호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 327-7','77호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(3,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 409-56','233호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 292-44','269호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 성산동 252-1','278호','젓가락 7개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 153-4','266호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 356-3','197호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 603-9','10호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 544','191호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 고척동 66-2','201호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 337','42호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 망원동 425-33','237호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 441-17','279호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 1126-35','146호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(2,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 648','245호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 성산동 533-1','76호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(4,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 186-7','272호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 360-17','65호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 476-19','288호','젓가락 8개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(6,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 639','25호','우유빼고 주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 327-7','91호','문 발로 차면서 배달해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 합정동 473','197호','올때 메로나' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 동교동 200-24','195호','배고파요 빨리와요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 94-10','141호','군만두 서비스주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 435-10','61호','앞집주소적었으니까 맞은편으로 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 402-5','103호','문앞에 놓고가세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(1,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 332-33','6호','저번에 닭다리 덜온거 갖다주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(10,  'scott' , 2, NOW()-200 , '서울 마포구 망원동 485-10','122호','맵게 해주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 구로동 486-7','247호','국물 많이주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 476-18','54호','단무지 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 구로구 신도림동 694','41호','상추 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(5,  'scott' , 2, NOW()-200 , '서울 마포구 상수동 310-20','10호','양파 많이' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(9,  'scott' , 2, NOW()-200 , '서울 마포구 서교동 343-2','234호','젓가락 9개주세요' );
insert into orderlist( shop_No, name, member_No, orderDate,  addr, addr2, comment)  values(7,  'scott' , 2, NOW()-200 , '서울 구로구 고척동 85-15','58호','우유빼고 주세요' );

desc orderlist;

select count(*) from orderlist;
;
;


